[context.production]
    environment = { PYTHON_VERSION = "3.8" }

[build]
    command = "uvicorn app.main:app --host=0.0.0.0 --port=${PORT:-5000} &"

[[redirects]]
    from = "/*"
    to = "/index.html"
    statut = 302
