[context.production]
    environment = { PYTHON_VERSION = "3.8" }

[build]
    command = "uvicorn main:app --host=0.0.0.0 --port=${PORT:-5000}"
    base = "./app/"

[[redirects]]
    from = "/*"
    to = "/"
